lab_4/urls.py
from django.conf.urls import url
from .views import *

app_name = 'lab_4'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^project$', project, name='project'),
    url(r'^contact$', contact, name='contact'),
    url(r'^register$', register, name='register'),
]

lab_5/urls.py
from django.urls import path
from .views import *

app_name = 'lab_5'

urlpatterns = [
    path('', index, name='index'),
    path('project', project, name='project'),
    path('contact', contact, name='contact'),
    path('form', activity_form, name='activity_form'),
    path('form/schedules', all_schedule, name='all_schedule'),
    path('form/delete_all', delete_all, name="delete_all"),
]

ppw_story/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('lab_4/', include('lab_4.urls')),
    path('lab_5/', include('lab_5.urls')),
]

lab_5/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

class Category(models.Model) :
    HOBBY = 'Hobbies'
    OUTDOOR = 'Outdoor'
    INDOOR = 'Indoor'
    STUDY = 'Study'
    WORK = 'Work'
    MISC = 'Miscellaneous'
    
    CATEGORY_CHOICES = (
        (HOBBY, 'Hobbies'),
        (OUTDOOR, 'Outdoor'),
        (INDOOR, 'Indoor'),
        (STUDY, 'Study'),
        (WORK, 'Work'),
        (MISC, 'Miscellaneous'),
    )

    category = models.CharField(
        max_length = 2,
        choices = CATEGORY_CHOICES,
        default = OUTDOOR,
    )
    
class Activity(models.Model) :
    activity_name = models.CharField(max_length = 32)
    time = models.DateTimeField(default = timezone.now)
    location =  models.CharField(max_length = 40) 
    category = models.ForeignKey(Category, on_delete = models.CASCADE)

lab_5/forms.py
from django import forms
from .models import Category

class Activity_Form(forms.Form):
    
    activity_name = forms.CharField(label='Name',
                    max_length = 27, widget = forms.TextInput(
                        attrs = {
                            'class':'form-control',
                            'placeholder':'Activity Name',
                            'required': True,
                        }
                    ))

    time = forms.DateTimeField(label='Date & Time',
                    widget = forms.DateTimeInput(
                        attrs = {
                            'class':'form-control',
                            'placeholder':'mm/dd/YY HH:MM  (Please use correct formatting and values)',
                            'required': True,
                        }
                    ))

    location = forms.CharField(label='Location',
                    max_length = 40, widget = forms.TextInput(
                        attrs = {
                            'class':'form-control',
                            'placeholder':'Activity Location',
                            'required': True,
                        }
                    ))

    category = forms.ChoiceField(label='Category',
                    choices = Category.CATEGORY_CHOICES,
                    widget = forms.Select(
                        attrs = {
                            'class':'form-control',
                            'required': True,
                        }
                    ))

lab_4/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html',)

def contact(request):
    return render(request, 'contact.html',)

def project(request):
    return render(request, 'project.html',)

def register(request):
    return render(request, 'register.html',)

lab_5/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import Activity_Form

def index(request):
    print('sini')
    return render(request, 'lab_5/index.html',)

def contact(request):
    return render(request, 'lab_5/contact.html',)

def project(request):
    return render(request, 'lab_5/project.html',)

def all_schedule(request):
    activities = Activity.objects.all()
    
    response = {'activities' : activities}
    return render(request, 'lab_5/all_schedule.html', response)

def delete_all(request):
    Activity.objects.all().delete()
    Category.objects.all().delete()
    
    return redirect('lab_5:all_schedule')

def activity_form(request):
    if request.method == 'POST' :
        form = Activity_Form(request.POST)
        if form.is_valid() :
            activity = Activity()
            category = Category(category = form.cleaned_data['category'])
            category.save()

            activity.activity_name = form.cleaned_data['activity_name']
            activity.time = form.cleaned_data['time']
            activity.location = form.cleaned_data['location']
            activity.category = category
            activity.save()

        return redirect('lab_5:all_schedule')
    else:
        form = Activity_Form()
        response = {'form' : form}
        return render(request, 'lab_5/form.html', response)

ppw_story/views.py
from django.shortcuts import redirect

def index(request):
    return redirect('lab_5/')

lab_4/templates/contact.html
<!doctype html>
{% load static %}
<html lang = "en-US">
<html>
    <head>
        <title>Skills and Contacts</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel = "stylesheet" href = "{% static "style.css" %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
        <body class = "bg-contact">
            <div class = "container">
                <header class ="black-bg-opacity-80 border-rounded white-text" id = "skill-header">
                    <h1 class = "h1-head-proj">Skills Possessed</h1>
                </header>

                {% include 'lab_4/navbar.html' %}

                <div class = "card black-bg-opacity-80 border-rounded border-solid-red-dark white-text" id = "card-skill">
                    <div class = "card-body">
                        <h1 class="text-center skill-text">HTML / CSS</h2>
                        <h1 class="text-center skill-text">JavaScript</h2>
                    </div>
                </div>

                <header class ="black-bg-opacity-80 border-rounded white-text" id = "contact-header">
                        <h1 class = "h1-head-proj">Contact</h1>
                </header>

                <div class = "black-bg-opacity-80 border-rounded border-solid-red-dark" id = "skill-section">
                    <div class="row" id="bottom-padding">
                        <div class="col-6 col-md-3 contact">
                            <a href = "https://mail.google.com"><img class ="contact-img" src = "{% static "images/email.png" %}"></a>
                        </div>
                        <div class="col-6 col-md-3 contact">
                            <a href = "#"><img class ="contact-img" src = "{% static "images/phone.png" %}"></a>
                        </div>
                        <div class="col-6 col-md-3 contact">
                            <a href = "http://www.linkedin.com"><img class ="contact-img" src = "{% static "images/linkedin.png" %}"></a>
                        </div>
                        <div class="col-6 col-md-3 contact">
                            <a href = "https://www.twitter.com"><img class ="contact-img" src = "{% static "images/twitter.png" %}"></a>
                        </div>
                    </div>
                </div>
            </div>
        </body>
</html>

lab_4/templates/index.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <title>Profile</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel = "stylesheet" href = "{% static "style.css" %}">
        
    </head>
    
    <body class = "bg-index">
        <div class = "container">
            <header>
                <h1 class = "h1-head white-text">Welcome to Josh Sudung's Profile</h1>
            </header>

            {% include 'lab_4/navbar.html' %}

            <div class="row black-bg-opacity-80 border-rounded border-solid-red-dark" id="content-top">
                <div class="col-sm-4">
                    <img id = "self-portrait" class = "border-solid-red-light" src = "{% static "images/person.jpeg" %}">
                </div>
                <div class="col-sm-8 border-solid-red-light" id="self-bio">
                    <div class = "white-text" >
                        <h2>Hello!</h2>
                        <h5>I'm Josh.</h3><br>
                        <h5>I'm a Web Developer</h3>
                    </div>
                </div>
                <div class="col-sm border-solid-red-light" id = "content-bottom">
                    <div class = "row">
                        <div class = "col-sm white-text">
                            <p>Currently involved in : </p>
                            <p class = "bottom-list">- Lorem ipsum dolor sit</p>
                            <p class = "bottom-list">- Constectur adipiscing</p>
                            <p class = "bottom-list">- Sed do eiusmod tempor</p>
                            <p class = "bottom-list">- Lorem ipsum dolor sit</p>
                            <p class = "bottom-list">- Constectur adipiscing</p>
                            <p class = "bottom-list">- Sed do eiusmod tempor</p>
                        </div>
                        <div class = "col-sm white-text" id = "right-modifier">
                            <p>Past Projects : </p>
                            <p class = "bottom-list">- Lorem ipsum dolor</p>
                            <p class = "bottom-list">- Sed do eiusmod tempor</p>
                            <p class = "bottom-list">- Lorem ipsum dolor</p>
                            <p class = "bottom-list">- Constectur adip</p>
                            <p class = "bottom-list">- Sed do eiusmod</p>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </body>
</html>

lab_4/templates/project.html
<!doctype html>
{% load static %}
<html lang="en-US">
<html>
    <head>
        <title>Projects</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel = "stylesheet" href = "{% static "style.css" %}">
    </head>
    <body class = "bg-project">
        <div class="container">
            <header class = "black-bg-opacity-80 border-rounded white-text" id = "project-header">
                <h1 class="h1-head">Current Projects</h1>
            </header>

            {% include 'lab_4/navbar.html' %}

            <div class="row black-bg-opacity-80 border-rounded border-solid-red-dark" id = "project-section">
                <div class="col-md-6">
                    <div class="card border-solid-red-light white-text" id="card-project">
                        <h3>Designing App</h3>
                        <h3>Logos</h3>
                        <img id = "proj-img-l" src = "{% static "images/proj_1.jpg" %}">
                        <h5>Lorem ipsum dolor</h5>
                        <h5>set amet dir</h5>
                    </div>
                </div>
                <div class = "col-md-6" id="right-proj-modifier">
                    <div class="card border-solid-red-light white-text" id="card-project">
                        <h3>Studying With</h3>
                        <h3>PeWe</h3>
                        <img id = "proj-img-r" src ="{% static "images/proj_2.jpeg" %}">
                        <h5>Lorem ipsum dolor</h5>
                        <h5 >set amet dir</h5>
                    </div>
                </div>
            </div>
        </div>
    </body>
   

</html>

lab_4/templates/register.html
<!doctype html>
{% load static %}
<html lang = "en-US">

<html>
    <head>
        <title>Profile</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel = "stylesheet" href = "{% static "style.css" %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
    <body class = "bg-regist">
        <div class = "container">
            <header class = "black-bg-opacity-80 border-rounded white-text" id = "contact-header">
                <h1 class="h1-head">Current Projects</h1>
            </header>

            {% include 'lab_4/navbar.html' %}

            <div class = "card black-bg-opacity-80 border-rounded border-solid-red-dark" id = "register-card">
                <form class="white-text">
                    <div class="form-group">
                        <label>Name</label>
                        <input type = "text" class="form-control" placeholder="Your Name"></input>
                    </div>
                    <div class="form-group">
                        <label>Birth Date</label>
                        <input type="date" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Email address</label>
                        <input type="email" class="form-control" placeholder="name@youremail.com">
                    </div>
                    <div class="form-group">
                        <label>Username</label>
                        <input type = "text" class="form-control" placeholder="Username"></input>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label>Confirm Password</label>
                        <input type="password" class="form-control"  placeholder="Enter your password again">
                    </div>
                    <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalCenter">Register</button>

                </form>
                
                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Registration Successful.</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                            Successfully registered your new account!
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'index' %}"><button type="button" class="btn btn-light">Back to Home</button></a>
                                <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </body>
</html>

lab_5/templates/lab_5/all_schedule.html
<!doctype html>
{% load static %}
<html lang = "en-US">

<html>
    <head>
        <title>Profile</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel = "stylesheet" href = "{% static "style.css" %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
    <body class = "bg-schedule">
        <div class = "container">
            <header class = "black-bg-opacity-80 border-rounded white-text" id = "contact-header">
                <h1 class="h1-head">Scheduling</h1>
            </header>

            {% include 'lab_5/navbar.html' %}

            <div class = "card black-bg-opacity-80 border-rounded border-solid-red-dark white-text" id = "register-card">
                <div class="row" id ="activity-row">
                    {% if activities %}
                        {% for activity in activities %}
                            <div class = "col-md-5 black-bg-opacity-80 border-rounded border-solid-red-dark" id = "activity-splitter">
                                <p>Name : {{  activity.activity_name }}</p>
                                <p>Date & Time : {{  activity.time }}</p>
                                <p>Location : {{  activity.location }}</p>
                                <p>Category : {{  activity.category.category }}</p>
                            </div>
                        {% endfor %}
                    {% else %}
                            <div class = "col-md text-center"><h5>No Schedule</h5></div>
                    {% endif %}
                </div>
                
                <div class="choices">
                    <a href = "{% url 'lab_5:activity_form' %}"><button type="button" class="btn btn-light" id="margin-bottom-right" data-dismiss="modal">Add new schedule</button></a>
                    <a><button type="button" class="btn btn-dark " data-dismiss="modal" data-toggle="modal" data-target="#exampleModalCenter">Delete all schedules</button></a>
                </div>

                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title black-text" id="exampleModalCenterTitle">Delete Schedules?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body black-text">
                            Do you want to delete all your schedules?
                            </div>
                            <div class="modal-footer">
                                <a href = "{% url 'lab_5:delete_all' %}"><button type="button" class="btn btn-danger black-text">Delete</button></a>
                                <button type="button" class="btn btn-dark" data-dismiss="modal">Back</button>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </body>
</html>

lab_5/templates/lab_5/contact.html
<!doctype html>
{% load static %}
<html lang = "en-US">
<html>
    <head>
        <title>Skills and Contacts</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel = "stylesheet" href = "{% static "style.css" %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
        <body class = "bg-contact">
            <div class = "container">
                <header class ="black-bg-opacity-80 border-rounded white-text" id = "skill-header">
                    <h1 class = "h1-head-proj">Skills Possessed</h1>
                </header>

                {% include 'lab_5/navbar.html' %}

                <div class = "card black-bg-opacity-80 border-rounded border-solid-red-dark white-text" id = "card-skill">
                    <div class = "card-body">
                        <h1 class="text-center skill-text">HTML / CSS</h2>
                        <h1 class="text-center skill-text">JavaScript</h2>
                    </div>
                </div>

                <header class ="black-bg-opacity-80 border-rounded white-text" id = "contact-header">
                        <h1 class = "h1-head-proj">Contact</h1>
                </header>

                <div class = "black-bg-opacity-80 border-rounded border-solid-red-dark" id = "skill-section">
                    <div class="row" id="bottom-padding">
                        <div class="col-6 col-md-3 contact">
                            <a href = "https://mail.google.com"><img class ="contact-img" src = "{% static "images/email.png" %}"></a>
                        </div>
                        <div class="col-6 col-md-3 contact">
                            <a href = "#"><img class ="contact-img" src = "{% static "images/phone.png" %}"></a>
                        </div>
                        <div class="col-6 col-md-3 contact">
                            <a href = "http://www.linkedin.com"><img class ="contact-img" src = "{% static "images/linkedin.png" %}"></a>
                        </div>
                        <div class="col-6 col-md-3 contact">
                            <a href = "https://www.twitter.com"><img class ="contact-img" src = "{% static "images/twitter.png" %}"></a>
                        </div>
                    </div>
                </div>
            </div>
        </body>
</html>

templates/lab_4/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark black-bg-opacity-80 border-rounded">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_4:index' %}">It's Me!<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_4:project' %}">Projects</a>
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_4:contact' %}">Skills & Contacts</a>
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_4:register' %}">Register</a>
        </div>
    </div>
</nav>

templates/lab_5/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark black-bg-opacity-80 border-rounded">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_5:index' %}">It's Me!<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_5:project' %}">Projects</a>
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_5:contact' %}">Skills & Contacts</a>
            <a class="nav-item nav-link white-text btn btn-danger" href="{% url 'lab_5:all_schedule' %}">Scheduling</a>
        </div>
    </div>
</nav>